### ISSUE TITLE
missing examples/ising_instances/santoro_80x80_neighbors.npy

### ISSUE THREAD

**Issue by ghost** [hadsed/pathintegral-qmc#2]
Two examples (santoro80.py and santoro80_omp.py) refer to the following file but it is not in the repo:

```
examples/ising_instances/santoro_80x80_neighbors.npy
```

running the example produces this error:

```
$ python santoro80.py 
True groundstate energy:  -10115.3067315
True energy per spin:  -1.58051667679
True magnetization:  -32.0
True magnetization per spin:  -0.005


Traceback (most recent call last):
  File "santoro80.py", line 283, in <module>
    neighbors = np.load('ising_instances/santoro_80x80_neighbors.npy')
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: 'ising_instances/santoro_80x80_neighbors.npy'
```

Is this file just missing from the repo or is there some auxiliary command to generate the file?

**Comment by ghost** [comment]
I found the comment lines in the santoro80.py examples and saw that they created the file when uncommented.
